---
# MUST READ: To generate a new Certificate Authorities; run this command on master node: $ sudo kubeadm token create --print-join-command
# token expires after one hour by default. 

- name: Join the worker node to the Kubernetes cluster
  shell: "kubeadm join 192.168.1.170:6443 --token kh03rv.ewd7z1p734y5763w --discovery-token-ca-cert-hash sha256:90dba077e30c76f86d2c10efdebca1d90fe86d0922219b245e639217bf39bf31"
  become: true

