- name: Enable Kernel Modules (overlay and br_netfilter)
  command: modprobe {{ item }}
  loop:
    - overlay
    - br_netfilter

- name: Add Kernel Configuration
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    reload: yes
  with_items:
    - { name: net.ipv4.ip_forward, value: 1 }
    - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
    - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }

- name: Reload Kernel Configuration
  command: sysctl --system 
