---
- name: Install Helm
  hosts: kube-master
  gather_facts: true
  become: true  # You may need root privileges to install Helm

  tasks:
    - name: Download Helm
      get_url:
        url: https://get.helm.sh/helm-v3.13.0-linux-amd64.tar.gz  # Update the URL for your platform
        dest: /tmp/helm.tar.gz
        mode: 0755

    - name: Extract Helm
      command: tar -zxvf /tmp/helm.tar.gz -C /tmp/
      args:
        creates: /tmp/linux-amd64/helm

    - name: Move Helm to /usr/local/bin
      command: mv /tmp/linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    - name: Clean up temporary files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/helm.tar.gz
        - /tmp/linux-amd64/

