---
- name: Install common Ubuntu Packages, Postfix, awscli, and Ansilbe 
  hosts: all
  become: true

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install common Ubuntu packages
    apt:
      name:
        - build-essential
        - curl
        - git
        - htop
        - tree
        - unzip
        - vim
        - wget
        - awscli
        - ansible
      state: present

  - name: Install Postfix
    apt:
      name: postfix
      state: present
 
  - name: Enable and start Postfix service
    service:
      name: postfix
      enabled: yes
